# 红外相机边缘检测系统配置文件

camera:
  device_id: 0
  width: 640
  height: 480
  fps: 30
  format: "YUY2"
  buffer_size: 4
  pixel_size_um: 3.4  # 单位：微米
  focal_length_mm: 2.6 # 单位：毫米
  fov_deg: 46          # 单位：度
  sensor_model: "GC0308"
  max_resolution: "640x480"
  module_size_mm: [25, 12, 6]
  object_distance_min_cm: 30
  output_formats: ["YUY2", "MJPEG"]
  lens_fno: 2.8
  efl_mm: 2.6
  tv_distortion: 1.8
  relative_illumination: 70
  ir_filter_nm: 850

processing:
  gaussian_kernel: [5, 5]
  clahe_clip_limit: 2.0
  clahe_tile_size: [8, 8]
  temporal_filter_size: 3

edge_detection:
  algorithm: "canny"
  canny_low_threshold: 200
  canny_high_threshold: 300
  sobel_kernel: 7
  temperature_threshold: 5.0
  hough_threshold: 100
  hough_min_line_length: 200
  hough_max_line_gap: 20

system:
  log_level: "INFO"
  max_memory_mb: 512
  enable_gpu: false
  output_dir: "./output"